#- name: Install werkzeug==0.16.0
#  sudo pip install --upgrade Flask
---

- name: Wait for updates / upgrades from user data script to release lock
  script: wait-for-apt-on-startup.sh

- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes
    upgrade: "yes" # Needs to be quoted
    force_apt_get: yes
    cache_valid_time: 86400 #One day

- name: Install required packages
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
    state: present
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python
      - python3
      - python-apt
      - python3-apt
      - python-pip
      - python3-pip
      - curl
      - jq
      - rsync